import "../../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ServicesLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="my-40">{children}</div>
      </body>
    </html>
  );
}
